### ISSUE TITLE
ProguardRules

### ISSUE THREAD

**Issue by v4ekmarev** [usedesk/Android_SDK#13]
Do you can add  proguard rules in documentation without these rules? I cant generate release build with enable proguard.

-keepclassmembers class ru.usedesk.chat_sdk.data.repository.api.entity.** { *; }
-keepclassmembers class ru.usedesk.chat_sdk.entity.** { *; }
-keepclassmembers class ru.usedesk.chat_sdk.data.repository.api.loader.socket._entity.** { *; }

**Comment by Uncreated** [comment]
These rules are required for the chat-sdk module with proguard enabled.
Could you provide more information about your issue?

**Comment by Uncreated** [comment]
Check out updated [proguard-rules.pro](https://github.com/usedesk/Android_SDK/blob/master/app/proguard-rules.pro) file. That may solve this issue.
