### ISSUE TITLE
(Feature request) Open KB article by id

### ISSUE THREAD

**Issue by timurgilfanov** [usedesk/Android_SDK#19]
Our team switched from Helpshift to UseDesk recently. One of the features we can not find in UseDesk is ability to show an article to user to explain how modify app permissions on Huawei phones, for example. Only option is to copy article to HTML and show it in local WebView. But it have many disadvantages: need to support both versions, code become more complicated. 

It there any reasons this feature is absent for Android? Our iOS developer says that UseDesk iOS SDK have it.

**Comment by nichvolod** [comment]
Hi there! 

Your colleague is right, we have this feature on iOS, but not at Android SDK yet. But, luckily, we are developing new KB for Android, where this feature will be available. I estimate that feature will be released by the end of April, 2023.

We would keep you updated ;)

**Comment by nichvolod** [comment]
Hi there!

Released https://github.com/usedesk/Android_SDK/releases/tag/4.1.0
