### ISSUE TITLE
Support android 14 and target sdk 34

### ISSUE THREAD

**Issue by andrey989152** [usedesk/Android_SDK#21]
Привет!
Можете пожалуйста поднять версию до 34 target sdk. На 34 версии нужно явно указывать тип запускаемого сервиса :)
А то ловим MissingForegroundServiceTypeException

**Comment by nichvolod** [comment]
Привет! Можем, готовим обновление. Ожидаем релиз на этой неделе. Как только выйдет в свет, напишу тут :)

**Comment by nichvolod** [comment]
Релизнуто https://github.com/usedesk/Android_SDK/releases/tag/4.2.0
