### ISSUE TITLE
Request to migrate ExoPlayer dependency to "androidx.media3" for better compatibility

### ISSUE THREAD

**Issue by anatoliyRodkin** [usedesk/Android_SDK#22]
I am currently integrating the UseDesk SDK into an Android project that has recently migrated to using androidx.media3 for media playback, which is the latest iteration of the ExoPlayer library under the AndroidX namespace. After the migration, we have encountered compatibility issues between the UseDesk SDK and the "androidx.media3" library, specifically related to class cast exceptions when attempting to use media playback functionalities provided by the SDK. 

An example of such an exception is:
_java.lang.ClassCastException: androidx.media3.ui.AspectRatioFrameLayout cannot be cast to com.google.android.exoplayer2.ui.AspectRatioFrameLayout_

This issue arises because the UseDesk SDK internally uses the older "com.google.android.exoplayer" package, while our project has migrated to the newer "androidx.media3" package, leading to conflicts between these dependencies.

Given the growing adoption of "androidx.media3" for its improvements and compatibility with the AndroidX ecosystem, we kindly request the consideration of migrating the UseDesk SDK's ExoPlayer dependency to "androidx.media3". This update would greatly enhance compatibility and ease integration efforts for projects that have adopted or plan to adopt the newer media library.

We understand that such migrations can involve significant updates, but we believe this change will benefit many developers in the community by ensuring better future compatibility and leveraging the latest improvements in media playback on Android.

Thank you for considering this request. We appreciate the work you do on the UseDesk SDK and look forward to any updates on this matter.

**Comment by nichvolod** [comment]
Hi there! Significant is not the best word to describe, we would say (it was tough, haha). 

Sure, we are preparing an update. We are expecting to release it this week. As soon as it's published, I'll post news here :)

**Comment by nichvolod** [comment]
Done! https://github.com/usedesk/Android_SDK/releases/tag/4.2.0
