### ISSUE TITLE
Приходят старые сообщения в чат

### ISSUE THREAD

**Issue by remain4life** [usedesk/Android_SDK#3]
При работе с приложением возникает проблема при смене пользователя - в `onMessagesReceived `имплементации `UsedeskActionListener `приходят сообщения, которые были отправлены другими пользователями до него. При разлогине я освобождаю чат (`UsedeskSdk.releaseChat`), при логине нового юзера в методе `UsedeskSdk.setUsedeskConfiguration` передаю другой `id `и номер телефона. После полной очистки данных приложения проблема исчезает. Кажется, что проблема возникает, т.к. полностью не очищается конфигурация. Как это правильно сделать? Метода по очистке не нашел, а параметр `UsedeskSdk.setUsedeskConfiguration` помечен как `@NonNull`. Пробовал при разлогине передавать в этот метод пустую конфигурацию (передавал пустые строки во все поля конструктора), не помогает.

**Comment by Uncreated** [comment]
Привет, если не поменять email, то ты получишь историю сообщений.
Убедись, что email отличается от предыдущего.

**Comment by remain4life** [comment]
Спасибо, так и есть
