### ISSUE TITLE
Duplicated UsedeskMessageClient

### ISSUE THREAD

**Issue by Villere** [usedesk/Android_SDK#5]
При неуспешной отправке файла клиентом, сообщения могут быть дублированы. При это одно сообщение будет помечено как SEND_FAILED, а второе как SUCCESSFULLY_SENT.

![Screenshot_20210421-150340_FD 19](https://user-images.githubusercontent.com/23175882/115550813-f5ffea00-a2b2-11eb-90fe-a719885fbd0f.jpg)

Шаги для воспроизведения:
1. Удостовериться в наличии интернет соединения (в моем случае я использовал WiFi)
3. Открыть чат
3. Прикрепить к сообщению файл из галереи (желательно большого размера, вопроизводилось при отправке изображений от 4Мб)
4. Нажать на кнопку отправить
5. Отключить интернет соединение (отключить WiFi)
6. Дождаться пока на новом сообщении не появится статус SEND_FAILED
7. Восстановить интернет соединение (включить WiFi)
8. Дождаться появления второго изображения

При этом, у этих двух сообщений будут разные ID: первый будет иметь отрицательный (что, как я понимаю, является локальным ID), второй положительный

Версия SDK: 3.1.8
Девайс: Samsung Galaxy S10

**Comment by Uncreated** [comment]
Проблема воспроизвелась, но пока что мы не можем её исправить т.к. это требует доработок на сервере.
