### ISSUE TITLE
Unable to reuse UsedeskChatSdk instance

### ISSUE THREAD

**Issue by Villere** [usedesk/Android_SDK#6]
При первичной инициализации чата все работает нормально (сообщения отправляются, listener получает события):
```
UsedeskChatSdk.setConfiguration(...)
val usedeskChat = UsedeskChatSdk.init(context)
usedeskChat.addActionListener(...)
usedeskChat.connect()
```
Завершение работы с чатом:
```
usedeskChat.removeActionListener(...)
usedeskChat.disconnect()
```

Если же переиспользовать инициализированный instance, listener не получает никаких сообщений. При отправке сообщениий всегда возвращается UsedeskSocketException.Error.DISCONNECTED:

```
val usedeskChat = UsedeskChatSdk.getInstance()   // usedeskChat != null
usedeskChat.addActionListener(...)
usedeskChat.connect()
...
usedeskChat.send(...)   // <- UsedeskSocketException.Error.DISCONNECTED
```

SDK version: 3.1.8
Device: Samsung Galaxy S10

**Comment by Uncreated** [comment]
Действительно, есть такая ошибка.
Исправил, будет опубликовано в ближайшем релизе.
Альтернативным решением может быть использование `UsedeskChatSdk.release(true)` для прекращения работы и повторный вызов `UsedeskChatSdk.init(context)` для возобновления.

**Comment by Uncreated** [comment]
Исправлено в v3.2.1
