### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by mrnorbertf** [usedesk/Android_SDK#7]
Добрый день,

получили рассылку, что signature теперь должна быть длинной не менее 64символа.
Здесь про это инфы нет, в чате тоже. Только в статье про виджет https://usedeskkb.atlassian.net/wiki/spaces/API/pages/293863434 .

Подскажет, где правда. 
Есть ли ограничение на UsedeskChatConfiguration.clientSignature или нет?

Заранее спасибо

**Comment by Uncreated** [comment]
Добрый день.
В sdk изменения не вносились, поэтому ограничений на данный момент нет.
После изменений в sdk старые версии сигнатур будут функционировать некоторое время.
