### ISSUE TITLE
Приходится дважды нажимать на кнопку назад.

### ISSUE THREAD

**Issue by vovadvortsov95** [usedesk/Android_SDK#8]
При первом запуске чата и нажатии на кнопку назад происходит переход к экрану с загрузкой вместо выхода из чата.

**Comment by Uncreated** [comment]
Стоит внимательно ознакомиться с разделом [Использование с GUI](https://github.com/usedesk/Android_SDK#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81-gui), в частности с реализацией вызова метода `onBackPressed()` у фрагмента чата.
